[package]
name = "is_basic"
version = "0.1.0"
authors = ["Isaac <isasca@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_input = "0.8.4"
