[package]
name = "is_basic-cli"
version = "0.1.0"
authors = ["isasca <zfac143@live.rhul.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_basic = {path = "../is_basic"}
